language: csharp
node_js:
- 6.3.1
os: linux		
dist: trusty		
sudo: required
services:
  - docker
dotnet: 1.0.1
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
install:
- dotnet restore
before_script:
solution: "./Docker.Web/Docker.Web.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- dotnet publish -c Release -o out
- docker build -t Docker.Web
- docker run -it --rm Docker.Web
