language: csharp
node_js:
- 6.3.1
os: linux		
dist: trusty		
sudo: required
services:
  - docker
dotnet: 1.0.1
install:
- dotnet restore
before_script:
solution: "./Docker.Web/Docker.Web.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- dotnet publish -c Release -o out
after_success:
  - ls
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $DOCKER_USER$REPO .
  - docker push $DOCKER_USER$REPO
  - cd "./Docker.Web/"
  - ls