language: csharp
node_js:
- 6.3.1
os: linux		
dist: trusty		
sudo: required
services:
  - docker
dotnet: 1.0.1
install:
- dotnet restore
before_script:
solution: "./Docker.Web/Docker.Web.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- dotnet publish -c Release -o out
- docker build -t DockerSample
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=siddharthashw/Docker-demo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO